# Generated by Django 5.1.1 on 2024-10-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
