# Generated by Django 5.1.1 on 2024-10-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_back_image_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/users_background_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/users_profile_images'),
        ),
    ]
